<?php
/**
 * Copyright (c) 2023-present GLS Croatia. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Inchoo (https://inchoo.net)
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \GLSCroatia\Shipping\ViewModel\ParcelShopDelivery $parcelShopDelivery */
$parcelShopDelivery = $block->getData('parcel_shop_delivery');

/** @var \Magento\Sales\Model\Order $order */
$order = $block->getParentBlock()->getOrder();

$isParcelShopDeliveryMethod = $order && $parcelShopDelivery->isParcelShopDeliveryMethod($order->getShippingMethod());
if ($isParcelShopDeliveryMethod) {
    $deliveryData = $parcelShopDelivery->getParcelShopDeliveryPointData($order);
}
?>

<?php if ($isParcelShopDeliveryMethod && $deliveryData->getData()): ?>
    <table>
        <tr>
            <td>
                <h3><?= $block->escapeHtml($order->getShippingDescription()) ?></h3>
                <p>
                    <?= $block->escapeHtml((string)$deliveryData->getData('name')) ?><br>
                    <?= $block->escapeHtml((string)$deliveryData->getData('contact/address')) ?><br>
                    <?= $block->escapeHtml((string)$deliveryData->getData('contact/city')) ?>, <?= $block->escapeHtml((string)$deliveryData->getData('contact/postalCode')) // phpcs:ignore ?><br>
                    <?= $block->escapeHtml((string)$deliveryData->getData('contact/countryCode')) ?><br>
                </p>
            </td>
        </tr>
    </table>
<?php endif; ?>
