<?php
/**
 * Copyright (c) 2023-present GLS Croatia. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Inchoo (https://inchoo.net)
 */

/** @var \GLSCroatia\Shipping\Block\Adminhtml\Sales\View\ParcelShopDelivery $block */

$order = $block->getOrder();
?>

<?php if ($order && $block->getIsParcelShopDelivery()): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml($order->getShippingDescription()) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div id="delivery-point-address">
                <?= $block->getChildHtml('address') ?>
            </div>

            <?php if ($order->canShip()): ?>
                <div id="deliver-data-change">
                    <gls-dpm-dialog id="gls-map-dialog" country="<?= $block->escapeHtmlAttr($block->getCountryCode()) ?>" language="<?= $block->escapeHtmlAttr($block->getMapLanguageCode()) ?>"></gls-dpm-dialog>
                    <button type="button" id="map-selector-button" class="action"><?= $block->escapeHtml(__('Change Delivery Point')) ?></button>
                </div>

                <script type="text/x-magento-init">
                    {
                        "#deliver-data-change": {
                            "GLSCroatia_Shipping/js/order/delivery-data/map-selector": {
                                "mapScriptUrl": "<?= /* @noEscape */ $block->getMapScriptUrl() ?>",
                                "saveUrl": "<?= /* @noEscape */ $block->getUrl('gls/deliveryPoint/save', ['order_id' => $order->getId()]) ?>",
                                "mapSelectorButtonId": "map-selector-button",
                                "glsMapDialogId": "gls-map-dialog",
                                "deliveryPointAddressId": "delivery-point-address"
                            }
                        }
                    }
                </script>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>
