<?php
/**
 * Copyright (c) 2023-present GLS Croatia. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Inchoo (https://inchoo.net)
 */

/** @var \Magento\Backend\Block\Template $block */

/** @var \GLSCroatia\Shipping\ViewModel\ParcelShopDelivery $parcelShopDelivery */
$parcelShopDelivery = $block->getData('parcel_shop_delivery');

/** @var \Magento\Sales\Block\Adminhtml\Order\View\Info $orderInfoBlock */
$orderInfoBlock = $block->getLayout()->getBlock('order_info');

$order = $orderInfoBlock->getOrder();

$isParcelShopDeliveryMethod = $order && $parcelShopDelivery->isParcelShopDeliveryMethod($order->getShippingMethod());
if ($isParcelShopDeliveryMethod) {
    $deliveryData = $parcelShopDelivery->getParcelShopDeliveryPointData($order);
}
?>

<?php if ($isParcelShopDeliveryMethod): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml($order->getShippingDescription()) ?></span>
        </div>
        <address class="admin__page-section-content">
            <?php if ($deliveryData->getData()): ?>
                <strong><?= $block->escapeHtml((string)$deliveryData->getData('id')) ?></strong><br>
                <?= $block->escapeHtml((string)$deliveryData->getData('name')) ?><br>
                <?= $block->escapeHtml((string)$deliveryData->getData('contact/address')) ?><br>
                <?= $block->escapeHtml((string)$deliveryData->getData('contact/city')) ?>, <?= $block->escapeHtml((string)$deliveryData->getData('contact/postalCode')) // phpcs:ignore ?><br>
                <?= $block->escapeHtml((string)$deliveryData->getData('contact/countryCode')) ?><br>
            <?php else: ?>
                <?= $block->escapeHtml(__('ParcelShop delivery data is missing.')) ?>
            <?php endif; ?>
        </address>
    </section>
<?php endif; ?>
