<?php
/**
 * Copyright (c) 2023-present GLS Croatia. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Inchoo (https://inchoo.net)
 */

/** @var \Magento\Backend\Block\Template $block */

/** @var \GLSCroatia\Shipping\ViewModel\PackagingGlsOptions $viewModel */
$viewModel = $block->getData('view_model');

/** @var \Magento\Sales\Model\Order\Shipment $shipment */
$shipment = $block->getParentBlock()->getShipment();
?>

<?php if ($viewModel->isGlsShippingMethod($shipment)): ?>
    <?php
    $storeId = (int)$shipment->getStoreId();
    $shipmentRequest = $viewModel->generateTempShipmentRequest($shipment);

    $isCodAllowed = $viewModel->isCodServiceAllowed($shipmentRequest);
    $isGuaranteed24hAllowed = $viewModel->isGuaranteed24hServiceAllowed($shipmentRequest);
    $isExpressDeliveryAllowed = $viewModel->isExpressDeliveryServiceAllowed($shipmentRequest);
    $isContactAllowed = $viewModel->isContactServiceAllowed($shipmentRequest);
    $isFlexibleDeliveryAllowed = $viewModel->isFlexibleDeliveryServiceAllowed($shipmentRequest);
    $isFlexibleDeliverySmsAllowed = $viewModel->isFlexibleDeliverySmsServiceAllowed($shipmentRequest);
    $isSmsAllowed = $viewModel->isSmsServiceAllowed($shipmentRequest, $storeId);
    $isSmsPreAdviceAllowed = $viewModel->isSmsPreAdviceServiceAllowed($shipmentRequest);
    $isAddresseeOnlyAllowed = $viewModel->isAddresseeOnlyServiceAllowed($shipmentRequest);
    $isInsuranceAllowed = $viewModel->isInsuranceServiceAllowed($shipmentRequest,)
    ?>
    <section class="admin__page-section" data-mage-init='{"GLSCroatia_Shipping/js/shipping/order/packaging/gls-options": {}}'>
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('GLS Options')) ?></span>
        </div>

        <div class="admin__control-table-wrapper admin__page-subsection">
            <table class="data-table admin__control-table admin__control-table">
                <thead>
                    <tr>
                        <?php if ($isCodAllowed): ?>
                            <th><?= $block->escapeHtml(__('COD Reference')) ?></th>
                        <?php endif; ?>
                        <?php if ($isGuaranteed24hAllowed): ?>
                            <th><?= $block->escapeHtml(__('Guaranteed 24h Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isExpressDeliveryAllowed): ?>
                            <th><?= $block->escapeHtml(__('Express Delivery Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isContactAllowed): ?>
                            <th><?= $block->escapeHtml(__('Contact Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isFlexibleDeliveryAllowed): ?>
                            <th><?= $block->escapeHtml(__('Flexible Delivery Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isFlexibleDeliverySmsAllowed): ?>
                            <th><?= $block->escapeHtml(__('Flexible Delivery SMS Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isSmsAllowed): ?>
                            <th><?= $block->escapeHtml(__('SMS Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isSmsPreAdviceAllowed): ?>
                            <th><?= $block->escapeHtml(__('SMS Pre-advice Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isAddresseeOnlyAllowed): ?>
                            <th><?= $block->escapeHtml(__('Addressee Only Service')) ?></th>
                        <?php endif; ?>
                        <?php if ($isInsuranceAllowed): ?>
                            <th><?= $block->escapeHtml(__('Insurance Service')) ?></th>
                        <?php endif; ?>
                        <th><?= $block->escapeHtml(__('Print Position')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php if ($isCodAllowed): ?>
                            <td>
                                <input type="text" name="cod_reference" class="input-text admin__control-text"
                                       value="<?= $block->escapeHtmlAttr($viewModel->getCodReference($shipmentRequest)) ?>">
                            </td>
                        <?php endif; ?>
                        <?php if ($isGuaranteed24hAllowed): ?>
                            <td>
                                <select name="guaranteed_24h" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('guaranteed_24h', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isExpressDeliveryAllowed): ?>
                            <td>
                                <select name="express_delivery" class="admin__control-select">
                                    <?php $configValue = (string)$viewModel->getFieldConfigValue('express_delivery', $storeId) ?>
                                    <?php foreach ($viewModel->getExpressDeliveryCodeOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (string)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isContactAllowed): ?>
                            <td>
                                <select name="cs1" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('cs1', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isFlexibleDeliveryAllowed): ?>
                            <td>
                                <select name="fds" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('fds', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isFlexibleDeliverySmsAllowed): ?>
                            <td>
                                <select name="fss" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('fss', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isSmsAllowed): ?>
                            <td>
                                <select name="sm1" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('sm1', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isSmsPreAdviceAllowed): ?>
                            <td>
                                <select name="sm2" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('sm2', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isAddresseeOnlyAllowed): ?>
                            <td>
                                <select name="aos" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('aos', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <?php if ($isInsuranceAllowed): ?>
                            <td>
                                <select name="ins" class="admin__control-select">
                                    <?php $configValue = $viewModel->getFieldConfigFlag('ins', $storeId) ?>
                                    <?php foreach ($viewModel->getYesNoOptions() as $optionData): ?>
                                        <?php $isSelected = $configValue === (bool)$optionData['value'] ?>
                                        <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        <?php endif; ?>
                        <td>
                            <select name="print_position" class="admin__control-select">
                                <?php $configValue = $viewModel->getFieldConfigValue('print_position', $storeId) ?>
                                <?php foreach ($viewModel->getPrintPositionOptions() as $optionData): ?>
                                    <?php $isSelected = (int)$configValue === (int)$optionData['value'] ?>
                                    <option value="<?= $block->escapeHtmlAttr($optionData['value']) ?>" <?= $isSelected ? 'selected' : '' ?>><?= $block->escapeHtml($optionData['label']) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </section>
<?php endif; ?>
