<?php
/**
 * Copyright (c) 2023-present GLS Croatia. All rights reserved.
 * See LICENSE.txt for license details.
 *
 * @author Inchoo (https://inchoo.net)
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \GLSCroatia\Shipping\ViewModel\ParcelShopDelivery $parcelShopDelivery */
$parcelShopDelivery = $block->getData('parcel_shop_delivery');

/** @var \Magento\Sales\Model\Order $order */
$order = $block->getParentBlock()->getOrder();

$isParcelShopDeliveryMethod = $order && $parcelShopDelivery->isParcelShopDeliveryMethod($order->getShippingMethod());
if ($isParcelShopDeliveryMethod) {
    $deliveryData = $parcelShopDelivery->getParcelShopDeliveryPointData($order);
}
?>

<?php if ($isParcelShopDeliveryMethod && $deliveryData->getData()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "GLSCroatia_Shipping/js/order/info/parcel-shop-delivery": {}
            }
        }
    </script>

    <script id="parcel-shop-delivery-template" type="text/x-magento-template">
        <br><br>
        <?= $escaper->escapeHtml((string)$deliveryData->getData('name')) ?><br>
        <?= $escaper->escapeHtml((string)$deliveryData->getData('contact/address')) ?><br>
        <?= $escaper->escapeHtml((string)$deliveryData->getData('contact/city')) ?>, <?= $escaper->escapeHtml((string)$deliveryData->getData('contact/postalCode')) // phpcs:ignore ?><br>
        <?= $escaper->escapeHtml((string)$deliveryData->getData('contact/countryCode')) ?><br>
    </script>
<?php endif; ?>
